name: Generate docs
on: workflow_dispatch
jobs:
  docs:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup
      env:
        HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK: 1
      run: |
        brew update
        brew install automake boost doxygen graphviz
    - name: Doxygen version
      run: |
        doxygen --version
    - name: Generate docs
      run: |
        tar xfz QuantLib-1.*.tar.gz
        cd QuantLib-1.*/
        ./configure
        make docs
    - name: Save docs as artifacts
      uses: actions/upload-artifact@v3
      with:
        name: reference-docs
        path: ./QuantLib-1.*/Docs/html/
