name: Build wheels
on: push
jobs:
  wheels-macos:
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v3
    - name: Setup
      run: |
        brew install boost
        rm /usr/local/lib/libboost_unit_test_framework*
    - name: Build QuantLib
      run: |
        tar xfz QuantLib-1.*.tar.gz
        cd QuantLib-1.*/
        ./configure --disable-shared --enable-unity-build CXXFLAGS="-O2 -g0 -Wall -Werror -stdlib=libc++ -mmacosx-version-min=10.9" LDFLAGS="-stdlib=libc++ -mmacosx-version-min=10.9"
        make -j 4 install
    - name: Install Python
      run: |
        wget https://www.python.org/ftp/python/3.7.9/python-3.7.9-macosx10.9.pkg
        sudo installer -pkg python-3.7.9-macosx10.9.pkg -target LocalSystem
        /Library/Frameworks/Python.framework/Versions/3.7/bin/python3 -m pip install -U pip wheel
        wget https://www.python.org/ftp/python/3.8.10/python-3.8.10-macosx10.9.pkg
        sudo installer -pkg python-3.8.10-macosx10.9.pkg -target LocalSystem
        /Library/Frameworks/Python.framework/Versions/3.8/bin/python3 -m pip install -U pip wheel
        wget https://www.python.org/ftp/python/3.9.12/python-3.9.12-macos11.pkg
        sudo installer -pkg python-3.9.12-macos11.pkg -target LocalSystem
        /Library/Frameworks/Python.framework/Versions/3.9/bin/python3 -m pip install -U pip wheel
        wget https://www.python.org/ftp/python/3.10.4/python-3.10.4-macos11.pkg
        sudo installer -pkg python-3.10.4-macos11.pkg -target LocalSystem
        /Library/Frameworks/Python.framework/Versions/3.10/bin/python3 -m pip install -U pip wheel
    - name: Build QuantLib wheels
      env:
        CXXFLAGS: -O2 -std=c++11 -stdlib=libc++ -mmacosx-version-min=10.9
        LDFLAGS: -stdlib=libc++ -mmacosx-version-min=10.9
      run: |
        tar xfz QuantLib-SWIG-1.*.tar.gz
        cd QuantLib-SWIG-1.*/Python
        /Library/Frameworks/Python.framework/Versions/3.7/bin/python3 setup.py bdist_wheel
        rm -rf build/
        /Library/Frameworks/Python.framework/Versions/3.8/bin/python3 setup.py bdist_wheel
        rm -rf build/
        /Library/Frameworks/Python.framework/Versions/3.9/bin/python3 setup.py bdist_wheel
        rm -rf build/
        /Library/Frameworks/Python.framework/Versions/3.10/bin/python3 setup.py bdist_wheel
        rm -rf build/
    - name: Test wheels
      run: |
        /Library/Frameworks/Python.framework/Versions/3.7/bin/python3 -m pip install --no-index --find-links QuantLib-SWIG-1.*/Python/dist/ QuantLib
        /Library/Frameworks/Python.framework/Versions/3.7/bin/python3 QuantLib-SWIG-*/Python/test/QuantLibTestSuite.py
        /Library/Frameworks/Python.framework/Versions/3.8/bin/python3 -m pip install --no-index --find-links QuantLib-SWIG-1.*/Python/dist/ QuantLib
        /Library/Frameworks/Python.framework/Versions/3.8/bin/python3 QuantLib-SWIG-*/Python/test/QuantLibTestSuite.py
        /Library/Frameworks/Python.framework/Versions/3.9/bin/python3 -m pip install --no-index --find-links QuantLib-SWIG-1.*/Python/dist/ QuantLib
        /Library/Frameworks/Python.framework/Versions/3.9/bin/python3 QuantLib-SWIG-*/Python/test/QuantLibTestSuite.py
        /Library/Frameworks/Python.framework/Versions/3.10/bin/python3 -m pip install --no-index --find-links QuantLib-SWIG-1.*/Python/dist/ QuantLib
        /Library/Frameworks/Python.framework/Versions/3.10/bin/python3 QuantLib-SWIG-*/Python/test/QuantLibTestSuite.py
    - name: Save wheels as artifacts
      uses: actions/upload-artifact@v2
      with:
        name: wheels-macos
        path: ./QuantLib-SWIG-*/Python/dist/*.whl
