name: Build wheels
on: push
jobs:
  wheels-macos:
    runs-on: macos-11
    strategy:
      fail-fast: false
      matrix:
        arch: [x86_64, arm64]
    steps:
    - uses: actions/checkout@v3
    - name: Setup
      run: |
        brew install boost
        rm /usr/local/lib/libboost_unit_test_framework*
    - name: Build QuantLib
      run: |
        tar xfz QuantLib-1.*.tar.gz
        cd QuantLib-1.*/
        ./configure --disable-shared --enable-unity-build
        make -j2 CXXFLAGS="-std=c++14 -g0 -O3 -fno-common -dynamic -DNDEBUG -fwrapv -arch ${{ matrix.arch }}" LDFLAGS="-fno-common -dynamic -DNDEBUG -fwrapv -arch ${{ matrix.arch }}"
        make install
    - name: Unpack QuantLib-SWIG
      run: |
        tar xfz QuantLib-SWIG-1.*.tar.gz
    - name: Build QuantLib wheels
      uses: pypa/cibuildwheel@v2.11.1
      env:
        CIBW_SKIP: cp36-*
        CIBW_ARCHS_MACOS: ${{ matrix.arch }}
        CXXFLAGS: -std=c++14 -g0 -O3
        CIBW_BUILD_VERBOSITY: 2
        CIBW_TEST_COMMAND: python {package}/test/QuantLibTestSuite.py
      with:
        package-dir: QuantLib-SWIG-*/Python
    - name: Save wheels as artifacts
      uses: actions/upload-artifact@v3
      with:
        name: wheels-macos-${{ matrix.arch }}
        path: ./wheelhouse/*.whl
  wheels-windows:
    runs-on: windows-2019
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: AMD64
            platform: x64
          - arch: x86
            platform: Win32
    steps:
    - uses: actions/checkout@v3
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1
    - name: Setup Boost
      run: |
        $Url = "https://boostorg.jfrog.io/artifactory/main/release/1.80.0/binaries/boost_1_80_0-msvc-14.2-64.exe"
        (New-Object System.Net.WebClient).DownloadFile($Url, "$env:TEMP\boost.exe")
        Start-Process -Wait -FilePath "$env:TEMP\boost.exe" "/SILENT","/SP-","/SUPPRESSMSGBOXES","/DIR=C:\local\boost-1.80.0"
    - name: Build QuantLib
      run: |
        Expand-Archive -Path QuantLib-1.28.zip -DestinationPath C:\local
        Copy-Item Build-2019.props C:\local\QuantLib-1.28\Build.props
        Copy-Item Directory.Build.props C:\local\QuantLib-1.28\
        cd C:\local\QuantLib-1.28\
        msbuild QuantLib.vcxproj -p:Configuration="Release (static runtime)" -p:Platform=${{ matrix.platform }}
        dir lib
    - name: Unpack QuantLib-SWIG
      run: |
        Expand-Archive -Path QuantLib-SWIG-1.28.zip -DestinationPath .
    - name: Build QuantLib wheels
      uses: pypa/cibuildwheel@v2.11.1
      env:
        QL_DIR: C:\local\QuantLib-1.28
        INCLUDE: C:\local\boost-1.80.0
        QL_STATIC_RUNTIME: 1
        CIBW_SKIP: cp36-*
        CIBW_ARCHS_WINDOWS: ${{ matrix.arch }}
        CIBW_BUILD_VERBOSITY: 2
        CIBW_TEST_COMMAND: python {package}/test/QuantLibTestSuite.py
      with:
        package-dir: QuantLib-SWIG-1.28/Python
    - name: Save wheels as artifacts
      uses: actions/upload-artifact@v3
      with:
        name: wheels-windows-${{ matrix.arch }}
        path: ./wheelhouse/*.whl
  wheels-linux-2010:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build wheels
      run: |
        docker run --rm -v $PWD:/work -w /work --entrypoint ./build_manylinux2010.sh quay.io/pypa/manylinux2010_x86_64
    - name: Save wheels as artifacts
      uses: actions/upload-artifact@v3
      with:
        name: wheels-linux-2010
        path: ./QuantLib-SWIG-*/Python/wheelhouse/*.whl
  wheels-linux-2014:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build wheels
      run: |
        docker run --rm -v $PWD:/work -w /work --entrypoint ./build_manylinux2014.sh quay.io/pypa/manylinux2014_x86_64
    - name: Save wheels as artifacts
      uses: actions/upload-artifact@v3
      with:
        name: wheels-linux-2014
        path: ./QuantLib-SWIG-*/Python/wheelhouse/*.whl
