name: Build wheels 01 - x86_64 manylinux
on: workflow_dispatch
jobs:
  wheels-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Unpack QuantLib and QuantLib-SWIG
      run: |
        tar xfz QuantLib-1.*.tar.gz
        tar xfz QuantLib-SWIG-1.*.tar.gz
    - name: Build QuantLib wheels
      uses: pypa/cibuildwheel@v2.11.1
      env:
        #CIBW_BUILD: "*-manylinux*"
        #CIBW_SKIP: cp36-*
        CIBW_BUILD: cp310-manylinux_x86_64
        CIBW_ARCHS_LINUX: x86_64
        CIBW_BUILD_VERBOSITY: 2
        CIBW_BEFORE_ALL_LINUX: ./before_all_linux.sh
        CIBW_ENVIRONMENT_LINUX: CXXFLAGS="-O3 -g0"
        CIBW_ENVIRONMENT_PASS_LINUX: CXXFLAGS
        CIBW_TEST_COMMAND: python {package}/test/QuantLibTestSuite.py
      with:
        package-dir: QuantLib-SWIG-1.*/Python
    - name: Save wheels as artifacts
      uses: actions/upload-artifact@v3
      with:
        name: wheels-linux-manylinux-x86_64
        path: ./wheelhouse/*.whl
